prefix = '.'
stop-words = 'stopwords.txt'

dataset = 'test'
corpus = 'line.toml'
index = 'idx'

query-judgements = "train_qrel.txt"

[[analyzers]]
method = 'ngram-word'
ngram = 1
filter = 'default-unigram-chain'

[query-runner]
query-path = "train_input.txt"
query-id-start = 0

[ranker]
method = "bm25"
k1 = 1.2
b = 0.75
k3 = 500