prefix = '.'
stop-words = 'stopwords.txt'

dataset = 'test'
corpus = 'line.toml'
index = 'idx'

query-judgements = "train_qrel_converted.txt"

[[analyzers]]
method = 'ngram-word'
ngram = 1
filter = 'default-unigram-chain'

[query-runner]
query-path = "train_input.txt"
query-id-start = 1
